# This compose file only contains the basic services needed for this module to work.
version: '3.7'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: 123mudar # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: GG-LEARNING # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - db:/var/lib/postgres
    ports:
      - "5440:5432"
    networks:
      - postgres-network

  adminer:
    image: adminer
    ports:
      - "8090:8080"
    networks:
      - postgres-network

networks:
  postgres-network:

volumes:
  db: